# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'open2see.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sqlite3

class Ui_OpenToViewTeamWindow(object):

    def viewing(self):
        self.playersinteam_list.clear()
        # retrieving the current_username that is logged in
        try123 = sqlite3.connect('trytest2.db')
        sql0 = "select current_username from extras where username='pai123';"
        trycurs = try123.cursor()
        trycurs.execute(sql0)
        current_useris = ""
        while True:
            rec = trycurs.fetchone()
            if rec == None:
                break
            current_useris = rec[0]

        teampicked=self.team_name_pick.currentText()    #current team from combo box

        #getting all players from the team list column in the table
        sql1 = "select "+teampicked+" from teams_of_"+current_useris+";"
        trycurs1 = try123.cursor()
        trycurs1.execute(sql1)
        list1=[]
        while True:
            rec = trycurs1.fetchone()
            if rec == None:
                break
            list1.append(rec[0])


        #removing teamname from the above list
        playerstooutput_list=[]
        for i in range(len(list1)):
            if (list1[i] != None and list1[i] != teampicked):
                playerstooutput_list.append(list1[i])

        #filling the list widget with only player names
        for i in range(len(playerstooutput_list)-1):
            self.playersinteam_list.insertItem(i, ""+ playerstooutput_list[i])

        self.value_of_team.setText(""+playerstooutput_list[len(playerstooutput_list)-1])

    def setupUi(self, OpenToViewTeamWindow):
        OpenToViewTeamWindow.setObjectName("OpenToViewTeamWindow")
        OpenToViewTeamWindow.resize(420, 531)
        self.centralwidget = QtWidgets.QWidget(OpenToViewTeamWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, 10, -1, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.value_of_team = QtWidgets.QLabel(self.centralwidget)
        self.value_of_team.setText("")
        self.value_of_team.setObjectName("value_of_team")
        self.horizontalLayout.addWidget(self.value_of_team)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.gridLayout.addLayout(self.horizontalLayout, 2, 0, 1, 1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setContentsMargins(-1, 10, -1, -1)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_6.addWidget(self.line)
        self.verticalLayout_3.addLayout(self.verticalLayout_6)
        self.gridLayout.addLayout(self.verticalLayout_3, 0, 0, 1, 1)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setContentsMargins(-1, 10, -1, -1)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.viewteamBtn = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.viewteamBtn.setFont(font)
        self.viewteamBtn.setObjectName("viewteamBtn")

        #button to view the team
        self.viewteamBtn.clicked.connect(self.viewing)

        self.verticalLayout_4.addWidget(self.viewteamBtn)
        self.gridLayout.addLayout(self.verticalLayout_4, 4, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(-1, 10, -1, -1)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.team_name_pick = QtWidgets.QComboBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.team_name_pick.setFont(font)
        self.team_name_pick.setObjectName("team_name_pick")

        # retrieving the current_username that is logged in
        try123 = sqlite3.connect('trytest2.db')
        sql0 = "select current_username from extras where username='pai123';"
        trycurs = try123.cursor()
        trycurs.execute(sql0)
        current_useris = ""
        while True:
            rec = trycurs.fetchone()
            if rec == None:
                break
            current_useris = rec[0]

        # to get all teams made by a particular user
        try123 = sqlite3.connect('trytest2.db')
        sql2 = "select * from teams_of_" + current_useris + " where " + current_useris + "='" + current_useris + "';"
        try1cursor = try123.cursor()
        try1cursor.execute(sql2)
        team_list = []
        while True:
            record = try1cursor.fetchone()
            if record == None:
                break
            l = len(record)
            for i in range(l):
                team_list.append(record[i])
                # filling the team combo box
        for i in range(1, l):
            self.team_name_pick.insertItem(i, team_list[i])

        self.horizontalLayout_4.addWidget(self.team_name_pick)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.gridLayout.addLayout(self.horizontalLayout_4, 1, 0, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.playersinteam_list = QtWidgets.QListWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.playersinteam_list.setFont(font)
        self.playersinteam_list.setObjectName("playersinteam_list")
        self.gridLayout_2.addWidget(self.playersinteam_list, 1, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem2, 1, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 0, 0, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_2, 3, 0, 1, 1)
        OpenToViewTeamWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(OpenToViewTeamWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 420, 22))
        self.menubar.setObjectName("menubar")
        OpenToViewTeamWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(OpenToViewTeamWindow)
        self.statusbar.setObjectName("statusbar")
        OpenToViewTeamWindow.setStatusBar(self.statusbar)

        self.retranslateUi(OpenToViewTeamWindow)
        QtCore.QMetaObject.connectSlotsByName(OpenToViewTeamWindow)

    def retranslateUi(self, OpenToViewTeamWindow):
        _translate = QtCore.QCoreApplication.translate
        OpenToViewTeamWindow.setWindowTitle(_translate("OpenToViewTeamWindow", "MainWindow"))
        self.label_2.setText(_translate("OpenToViewTeamWindow", "Value of your team-"))
        self.label.setText(_translate("OpenToViewTeamWindow", "View your Dream Teams here"))
        self.viewteamBtn.setText(_translate("OpenToViewTeamWindow", "View Team"))
        self.label_3.setText(_translate("OpenToViewTeamWindow", "Players :"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_OpenToViewTeamWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())