# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'signingup.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import *
from ak8 import *
from PyQt5.QtWidgets import QMessageBox
import sqlite3
import sys

class Ui_SignUpWindow(object):

    def quitpage(self):
        sys.exit()

    def signupBtnclicked(self):


        try123 = sqlite3.connect('trytest2.db')
        sql0 = "SELECT username from extras ;"
        try1cursor = try123.cursor()
        try1cursor.execute(sql0)
        username_list1 = []
        result = try1cursor.fetchall()
        for record in result:
            username_list1.append(record[0])

        #checking if username exists in database
        if (self.username_entry.text() in username_list1):
            self.showpopup1()
        else :                                                                                          #when username is new
            # when passwords don't match
            if (self.password_entry.text() != self.confpassword_entry.text()):
                self.showpopup()

            elif (self.username_entry.text() != "" and self.password_entry.text() != "" and self.confpassword_entry.text() != "" and self.firstteamname_entry.text() != "") :  # when passwords mactch
                try1234 = sqlite3.connect('trytest2.db')

                # updating extras table to add username, password and current_team
                sql1 = "insert into extras (username, password, current_team) " \
                       "values ('" + self.username_entry.text() + "', '" + self.password_entry.text() + "', '" + self.firstteamname_entry.text() + "');"
                try1cursor = try1234.cursor()
                try:
                    try1cursor.execute(sql1)
                    try1234.commit()
                    print("inserted in exrtaas successfully")
                except:
                    print("error in inserting in extras")

                # updating extras table to update current_user
                sql2 = "update extras set current_username = '" + self.username_entry.text() + "' where username='pai123';"
                try2cursor = try1234.cursor()
                try:
                    try2cursor.execute(sql2)
                    try1234.commit()
                    print("inserted in exrtaas successfully")
                except:
                    print("error in inserting in extras")


                #creating new table to store teams
                sql3 = "create table teams_of_"+self.username_entry.text()+" ( "+self.username_entry.text()+" varchar (20) , "+self.firstteamname_entry.text()+" varchar (20) );"
                try3cursor = try1234.cursor()
                try:
                    try3cursor.execute(sql3)
                    try1234.commit()
                    print("created table successfully")
                except:
                    print("error in creating table")

                #inserting in the above table of user teams
                sql4 = "insert into teams_of_" + self.username_entry.text() + " values ('" + self.username_entry.text() + "', '" + self.firstteamname_entry.text() + "');"
                try4cursor = try1234.cursor()
                try:
                    try4cursor.execute(sql4)
                    try1234.commit()
                    print("created table successfully")
                except:
                    print("error in creating table")

                #disabling all buttons until i find a way to close window
                self.username_entry.setEnabled(False)
                self.username_entry.repaint()
                self.password_entry.setEnabled(False)
                self.password_entry.repaint()
                self.confpassword_entry.setEnabled(False)
                self.confpassword_entry.repaint()
                self.firstteamname_entry.setEnabled(False)
                self.firstteamname_entry.repaint()
                self.signupBtn.setEnabled(False)
                self.signupBtn.repaint()

                #jumping to next window
                self.window = QtWidgets.QMainWindow()
                self.ui = Ui_HomePage()
                self.ui.setupUi(self.window)
                self.window.show()

            else :
                self.showpopup2()

    def showpopup(self):
        msg = QMessageBox()
        msg.setWindowTitle("Error!")
        msg.setWindowTitle("Error!")
        msg.setIcon(QMessageBox.Warning)
        msg.setText("Passwords do not match!")
        x = msg.exec_()

    def showpopup1(self):
        msg = QMessageBox()
        msg.setWindowTitle("Error!")
        msg.setIcon(QMessageBox.Warning)
        msg.setText("User already exists! Please choose a different username.")
        x = msg.exec_()

    def showpopup2(self):
        msg = QMessageBox()
        msg.setWindowTitle("Error!")
        msg.setIcon(QMessageBox.Warning)
        msg.setText("Please fill all the details.")
        x = msg.exec_()


    def setupUi(self, SignUpWindow):
        SignUpWindow.setObjectName("SignUpWindow")
        SignUpWindow.resize(643, 454)
        self.centralwidget = QtWidgets.QWidget(SignUpWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_4.addWidget(self.label_5)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_4.addWidget(self.line)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_4.addWidget(self.label_6)
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_4.addWidget(self.line_2)
        self.verticalLayout.addLayout(self.verticalLayout_4)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(128, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.username_entry = QtWidgets.QLineEdit(self.groupBox)
        self.username_entry.setObjectName("username_entry")
        self.horizontalLayout.addWidget(self.username_entry)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        spacerItem2 = QtWidgets.QSpacerItem(140, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.password_entry = QtWidgets.QLineEdit(self.groupBox)
        self.password_entry.setObjectName("password_entry")
        self.password_entry.setEchoMode(QtWidgets.QLineEdit.Password)
        self.horizontalLayout_2.addWidget(self.password_entry)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        spacerItem4 = QtWidgets.QSpacerItem(82, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.confpassword_entry = QtWidgets.QLineEdit(self.groupBox)
        self.confpassword_entry.setObjectName("confpassword_entry")
        self.confpassword_entry.setEchoMode(QtWidgets.QLineEdit.Password)
        self.horizontalLayout_3.addWidget(self.confpassword_entry)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem5)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem6)
        self.firstteamname_entry = QtWidgets.QLineEdit(self.groupBox)
        self.firstteamname_entry.setObjectName("firstteamname_entry")
        self.horizontalLayout_4.addWidget(self.firstteamname_entry)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem7)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.verticalLayout.addWidget(self.groupBox)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.quitBtn = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.quitBtn.setFont(font)
        self.quitBtn.setObjectName("quitBtn")

        #quitbtn function call
        self.quitBtn.clicked.connect(self.quitpage)

        self.horizontalLayout_5.addWidget(self.quitBtn)
        self.signupBtn = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.signupBtn.setFont(font)
        self.signupBtn.setObjectName("signupBtn")

        #calling signupbtnclickedfn
        self.signupBtn.clicked.connect(self.signupBtnclicked)

        self.horizontalLayout_5.addWidget(self.signupBtn)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem8)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        SignUpWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(SignUpWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 643, 22))
        self.menubar.setObjectName("menubar")
        SignUpWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(SignUpWindow)
        self.statusbar.setObjectName("statusbar")
        SignUpWindow.setStatusBar(self.statusbar)

        self.retranslateUi(SignUpWindow)
        QtCore.QMetaObject.connectSlotsByName(SignUpWindow)

    def retranslateUi(self, SignUpWindow):
        _translate = QtCore.QCoreApplication.translate
        SignUpWindow.setWindowTitle(_translate("SignUpWindow", "SignUp"))
        self.label_5.setText(_translate("SignUpWindow", "Fantasy Premier League"))
        self.label_6.setText(_translate("SignUpWindow", "SignUp today and start your career as the manager of your dream team!"))
        self.groupBox.setTitle(_translate("SignUpWindow", "Enter your details here:"))
        self.label.setText(_translate("SignUpWindow", "User Name"))
        self.label_2.setText(_translate("SignUpWindow", "Password"))
        self.label_3.setText(_translate("SignUpWindow", "Confirm Password"))
        self.label_4.setText(_translate("SignUpWindow", "Name of your First Team"))
        self.quitBtn.setText(_translate("SignUpWindow", "Quit"))
        self.signupBtn.setText(_translate("SignUpWindow", "SignUp"))

#
# if __name__ == "__main__" :
#     print("still ran")
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     MainWindow = QtWidgets.QMainWindow()
#     ui = Ui_SignUpWindow()
#     ui.setupUi(MainWindow)
#     MainWindow.show()
#     sys.exit(app.exec_())





