# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'signup2.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from ak8 import *
from signupss1 import *
import sqlite3
from PyQt5.QtWidgets import QMessageBox

class Ui_MainWindow(object):

    # check login creds and open home page
    def openmainpage(self):
        try12 = sqlite3.connect('trytest2.db')
        sql1 = "SELECT * from extras;"
        try1cursor = try12.cursor()
        try1cursor.execute(sql1)
        flag1 = []  #keep track of user existing; 0 - exists, 1 - does not
        flag2 = []  #keep track of password existing; 0 - exists, 1 - does not
        while True:
            record = try1cursor.fetchone()
            if record == None:
                break
            if (record[0] == self.user_name.text()):
                flag2.append(0)
                if (record[1] == self.password.text()):
                    flag1.append(0)

                    # updating the current user in extras table
                    sql2 = "update extras set current_username = '" + self.user_name.text() + "' where username='pai123';"
                    try2cursor = try12.cursor()
                    try:
                        try2cursor.execute(sql2)
                        try12.commit()
                        print("inserted in exrtaas successfully")
                    except:
                        print("error in inserting in extras")


                    MainWindow.close()
                    self.window = QtWidgets.QMainWindow()
                    self.ui = Ui_HomePage()
                    self.ui.setupUi(self.window)
                    self.window.show()
                    break
                else :
                    flag1.append(1) #password wrong
            else:
                flag2.append(1)     #username wrong

        if (0 not in flag2):
            self.popupWrUser()
        elif (0 not in flag1):
            self.popupWrPass()


        # sql2 = "select username from extras"
        # try2cursor = try12.cursor()
        # try2cursor.execute(sql2)
        # usermames=[]
        # while True:
        #     record = try2cursor.fetchone()
        #     if record == None:
        #         break
        #     usermames.append(record[0])
        #
        # if (self.user_name.text() not in usermames):
        #     self.popupWrUser()
        # else :
        #     self.popupWrPass()


    def opensignuppage(self):
        MainWindow.close()
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_SignUpWindow()
        self.ui.setupUi(self.window)
        self.window.show()


    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(450, 300)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_3 = QtWidgets.QHBoxLayout()
        self.verticalLayout_3.setContentsMargins(-1, 0, -1, -1)
        self.verticalLayout_3.setObjectName("verticalLayout_3")

        #fantasy premier league text
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)

        # creating pushbutton2 in Fantasy Premier League
        self.pushButton1 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton1.setObjectName("pushButton1")
        self.pushButton1.clicked.connect(self.showAboutAppMsg)
        self.verticalLayout_3.addWidget(self.pushButton1)

        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem1)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        spacerItem2 = QtWidgets.QSpacerItem(30, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.user_name = QtWidgets.QLineEdit(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.user_name.setFont(font)
        self.user_name.setObjectName("user_name")
        self.horizontalLayout.addWidget(self.user_name)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.password = QtWidgets.QLineEdit(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.password.setFont(font)
        self.password.setObjectName("password")
        self.password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.horizontalLayout_2.addWidget(self.password)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem5)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_4.addWidget(self.groupBox)
        self.verticalLayout_5.addLayout(self.verticalLayout_4)
        spacerItem6 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        self.verticalLayout_5.addItem(spacerItem6)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.resetBtn = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.resetBtn.setFont(font)
        self.resetBtn.setObjectName("resetBtn")
        self.horizontalLayout_3.addWidget(self.resetBtn)
        self.loginBtn = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.loginBtn.setFont(font)
        self.loginBtn.setObjectName("loginBtn")

        # calling fn to check login and open home page
        self.loginBtn.clicked.connect(self.openmainpage)

        self.horizontalLayout_3.addWidget(self.loginBtn)
        self.signuphere_label = QtWidgets.QLabel(self.centralwidget)
        self.signuphere_label.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.signuphere_label.setObjectName("signuphere_label")
        self.horizontalLayout_3.addWidget(self.signuphere_label)
        self.signUpBtn = QtWidgets.QPushButton(self.centralwidget)
        self.signUpBtn.setObjectName("signUpBtn")
        self.signUpBtn.clicked.connect(self.opensignuppage)
        self.horizontalLayout_3.addWidget(self.signUpBtn)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem7)
        self.verticalLayout_5.addLayout(self.horizontalLayout_3)
        self.verticalLayout_6.addLayout(self.verticalLayout_5)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem8)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 450, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.resetBtn.clicked.connect(self.password.clear)
        self.resetBtn.clicked.connect(self.user_name.clear)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Sign In"))
        self.label_3.setText(_translate("MainWindow", "Fantasy Premier League"))
        self.groupBox.setTitle(_translate("MainWindow", "Sign In"))
        self.pushButton1.setText(_translate("MainWindow", "About"))
        self.label.setText(_translate("MainWindow", "User Name"))
        self.label_2.setText(_translate("MainWindow", "Password"))
        self.resetBtn.setText(_translate("MainWindow", "Reset"))
        self.loginBtn.setText(_translate("MainWindow", "Login"))
        self.signuphere_label.setText(_translate("MainWindow", "New User? To Sign up Click"))
        self.signUpBtn.setText(_translate("MainWindow", "Here"))

    def popupWrPass(self):
        msg = QMessageBox()
        msg.setWindowTitle("Team Saved!")
        msg.setIcon(QMessageBox.Warning)
        msg.setText("Incorrect Password!")
        x = msg.exec_()

    def popupWrUser(self):
        msg = QMessageBox()
        msg.setWindowTitle("Team Saved!")
        msg.setIcon(QMessageBox.Warning)
        msg.setText("User does not exist! Please Sign up.")
        x = msg.exec_()

    def userguideShow(self):
        msg = QMessageBox()
        msg.setWindowTitle("Team Saved!")
        msg.setIcon(QMessageBox.Warning)
        msg.setText("User does not exist! Please Sign up.")
        x = msg.exec_()

    def showAboutAppMsg(self):
        msg = QMessageBox()
        msg.setWindowTitle("Team Saved!")
        msg.setIcon(QMessageBox.Information)
        msg.setText("Fantasy Premier League is a team building game.\n"
                    "-> Here, the user must pick a team of 11 Indian cricketers - "
                    "4 Batsmen, 4 Bowlers, 2 All Rounders and 1 Wicket-Keeper. The cricketers are assigned Value points based on their careers.\n"
                    "-> Each user is given 1000 Value points that he/she can spend to build the best team he/she desires.\n"
                    "-> The cricketers are given points based on their performance in the 2011 ICC Men's Circket World Cup.\n"
                    "-> India was represented by a 15 man team and played a total of 9 matches.\n"
                    "-> The total points of the team built by the user is evaluated by a variety of criteria as explained later.\n\n"
                    "Hope you enjoy the game! Get creative and compete with the best!")
        x = msg.exec_()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())


