# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'teamName.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from ak8 import *
import sqlite3
import sys
from PyQt5.QtWidgets import QMessageBox

class Ui_teamNameWindow(object):
    def openmainpage(self):
        # self.window = QtWidgets.QMainWindow()
        # self.ui = Ui_MainPage()
        # self.ui.setupUi(self.window)
        # self.window.show()
        print("yeah")

    def showpopup(self):
        msg = QMessageBox()
        msg.setWindowTitle("Error!")
        msg.setIcon(QMessageBox.Warning)
        msg.setText("You have a team with this name! Please use a different name.")
        x = msg.exec_()

    def confirmedfunction(self):

        # retrieving the current_username that is logged in
        try123 = sqlite3.connect('trytest2.db')
        sql0 = "select current_username from extras where username='pai123';"
        trycurs = try123.cursor()
        trycurs.execute(sql0)
        current_useris = ""
        while True:
            rec = trycurs.fetchone()
            if rec == None:
                break
            current_useris = rec[0]

        # inserting new team for the user
        #first getting count of number of rows in table, i.e., getting number of teams made by user and the teams also
        try123 = sqlite3.connect('trytest2.db')
        sql2 = "select * from teams_of_"+current_useris+" where "+current_useris+"='"+current_useris+"';"
        try1cursor = try123.cursor()
        try1cursor.execute(sql2)
        team_names=[]
        while True:
            record = try1cursor.fetchone()
            if record == None:
                break
            l = len(record)
            for i in range(l):
                team_names.append(record[i])


        if (self.team_name.text() not in team_names):
            # updating current_team
            try12 = sqlite3.connect('trytest2.db')
            name = self.team_name.text()
            sql1 = "UPDATE extras SET current_team='" + name + "' WHERE username='" + current_useris + "';"
            print(sql1)
            try1cursor = try12.cursor()
            try:
                try1cursor.execute(sql1)
                try12.commit()
                print("record updated successfully")
            except:
                print("error in update operation")

            # adding column name as team name
            try1234 = sqlite3.connect('trytest2.db')
            sql4 = "ALTER TABLE teams_of_" + current_useris + " ADD " + self.team_name.text() + " Varchar(255);"  # adding column name as team name
            try3cursor = try1234.cursor()
            try:
                try3cursor.execute(sql4)
                try1234.commit()
                print("alter updated successfully")
            except:
                print("error in altering operation")

            # adding the team name under that column
            sql5 = "update teams_of_" + current_useris + " set " + self.team_name.text() + "= '" + self.team_name.text() + "' where " + current_useris + "='" + current_useris + "';"
            try4cursor = try1234.cursor()
            try:
                try4cursor.execute(sql5)
                try1234.commit()
                print("team updated successfully")
            except:
                print("error in updating team operation")
        else :
            self.showpopup()
        # #updating point_available
        # sql2 = "UPDATE extras SET points_available=100 WHERE username='pai123';"
        # print(sql2)
        # try2cursor = try12.cursor()
        # try:
        #     try2cursor.execute(sql2)
        #     try12.commit()
        #     print("points_available updated successfully")
        # except:
        #     print("error in updating points_available operation")
        #
        # #updating points_used
        # sql3 = "UPDATE extras SET points_used=0 WHERE username='pai123';"
        # try3cursor = try12.cursor()
        # try:
        #     try3cursor.execute(sql3)
        #     try12.commit()
        #     print("points_used updated successfully")
        # except:
        #     print("error in updating points_available operation")

        # updating players into each team column
        # sql6 = "insert into pai123_teams (team_name_2) values ('hi'), ('two'), ('theree');"
        # try5cursor = try1234.cursor()
        # try:
        #     try5cursor.execute(sql6)
        #     try1234.commit()
        #     print("team updated111 successfully")
        # except:
        #     print("error in updating111 team operation")

        # sql7 = "select team_name_2 from pai123_teams; "
        # try7cursor = try1234.cursor()
        # try7cursor.execute(sql7)
        # while True:
        #     record = try7cursor.fetchone()
        #     if record == None:
        #         break
        #     print(record)

    def setupUi(self, teamNameWindow):
        teamNameWindow.setObjectName("teamNameWindow")
        teamNameWindow.resize(350, 250)
        self.centralwidget = QtWidgets.QWidget(teamNameWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_6.addWidget(self.label_2)
        self.gridLayout.addLayout(self.verticalLayout_6, 0, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.team_name = QtWidgets.QLineEdit(self.groupBox)
        self.team_name.setObjectName("team_name")
        self.horizontalLayout.addWidget(self.team_name)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.gridLayout.addWidget(self.groupBox, 1, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.backBtn = QtWidgets.QPushButton(self.centralwidget)
        self.backBtn.setObjectName("backBtn")
        self.backBtn.clicked.connect(self.openmainpage)
        self.backBtn.clicked.connect(teamNameWindow.close)
        self.horizontalLayout_3.addWidget(self.backBtn)
        self.confirmnameBtn = QtWidgets.QPushButton(self.centralwidget)
        self.confirmnameBtn.setObjectName("confirmnameBtn")

        #closing and calling function
        self.confirmnameBtn.clicked.connect(teamNameWindow.close)
        self.confirmnameBtn.clicked.connect(self.confirmedfunction)

        self.horizontalLayout_3.addWidget(self.confirmnameBtn)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.gridLayout.addLayout(self.horizontalLayout_3, 2, 0, 1, 1)
        teamNameWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(teamNameWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 478, 22))
        self.menubar.setObjectName("menubar")
        teamNameWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(teamNameWindow)
        self.statusbar.setObjectName("statusbar")
        teamNameWindow.setStatusBar(self.statusbar)

        self.retranslateUi(teamNameWindow)
        QtCore.QMetaObject.connectSlotsByName(teamNameWindow)

    def retranslateUi(self, teamNameWindow):
        _translate = QtCore.QCoreApplication.translate
        teamNameWindow.setWindowTitle(_translate("teamNameWindow", "TeamName"))
        self.label_2.setText(_translate("teamNameWindow", "Create a New Team"))
        self.groupBox.setTitle(_translate("teamNameWindow", "Time to get creative!"))
        self.label.setText(_translate("teamNameWindow", "Enter your team name"))
        self.backBtn.setText(_translate("teamNameWindow", "Back"))
        self.confirmnameBtn.setText(_translate("teamNameWindow", "Confirm"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_teamNameWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())